export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100">
      <header className="border-b border-zinc-800 px-6 py-4">
        <div className="max-w-3xl mx-auto flex items-center justify-between">
          <a href="/" className="text-lg font-semibold text-white">Corkeapp</a>
          <a href="/dashboard" className="text-sm text-zinc-400 hover:text-white">Open app</a>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
          <p className="text-zinc-500 text-sm">Last updated: May 2025</p>
        </div>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">1. Acceptance of Terms</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">By accessing or using Corkeapp you agree to be bound by these Terms of Service. If you do not agree to these terms do not use the service.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">2. Description of Service</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">Corkeapp is an independent AI-powered tool designed to assist CAD engineers with troubleshooting, macro generation, and API reference. It is not affiliated with, endorsed by, or connected to Dassault Systèmes, Autodesk, or any CAD software vendor.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">3. No Professional Engineering Advice</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">The information and AI-generated content provided by Corkeapp is for informational purposes only and does not constitute professional engineering advice. All AI-generated outputs must be independently verified by a qualified engineer before use in any production environment, manufacturing process, or safety-critical application. Corkeapp expressly disclaims any liability for damages arising from reliance on its outputs.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">4. AI Generated Content</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">Responses generated by the AI assistant may contain errors, inaccuracies, or outdated information. AI outputs are not guaranteed to be correct, complete, or suitable for any particular purpose. You use AI-generated content entirely at your own risk.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">5. Limitation of Liability</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">To the maximum extent permitted by applicable law, Corkeapp and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages including but not limited to loss of data, loss of profits, file corruption, project delays, or business interruption arising from your use of or inability to use the service.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">6. Acceptable Use</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">You agree not to misuse the service. Prohibited activities include but are not limited to: attempting to circumvent rate limits or access controls, using automated scripts to abuse the AI endpoint, reverse engineering the service, or using the service for any unlawful purpose.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">7. License Keys</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">Pro license keys are issued for personal use only and may not be shared, sold, or transferred. Corkeapp reserves the right to invalidate any license key that is found to be in use by multiple parties.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">8. Modifications to Service</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">Corkeapp reserves the right to modify, suspend, or discontinue the service at any time without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation of the service.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">9. Changes to Terms</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">We reserve the right to update these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.</p>
        </section>
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-white">10. Governing Law</h2>
          <p className="text-zinc-400 text-sm leading-relaxed">These terms shall be governed by and construed in accordance with applicable law. Any disputes arising from these terms or your use of the service shall be resolved through binding arbitration.</p>
        </section>
      </main>
      <footer className="border-t border-zinc-800 px-6 py-4">
        <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-2">
          <p className="text-zinc-600 text-xs">Corkeapp is an independent tool and is not affiliated with, endorsed by, or connected to Dassault Systèmes or any CAD software vendor.</p>
          <div className="flex gap-4">
            <a href="/terms" className="text-zinc-500 text-xs hover:text-white">Terms of Service</a>
            <a href="/privacy" className="text-zinc-500 text-xs hover:text-white">Privacy Policy</a>
          </div>
        </div>
      </footer>
      </div>
  );
}